import "./globals.css";
import type { Metadata } from "next";
import { BsTrello } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Trello App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href='/trello.svg' />
      </head>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
